### ISSUE TITLE
Setting a custom endpoint

### ISSUE THREAD

**Issue by kirksgithub** [dialectlabs/react#110]
I have two questions (not issues)

1. I noticed how the endpoint is taking the standard wallet adapter endpoint and is set as a global for the dapp, is there any way to override this only for dialect and to manually set the endpoint?
2. The react example uses:
`const DIALECT_PUBLIC_KEY = new PublicKey(
        'D2pyBevYb6dit1oCx6e8vCxFK9mBeYCRe8TTntk2Tm98'
    );`
Should this dapp key be used for the NotificationsButton because I do see a screenshot on the website using the variable "YOUR_PROJECT_PUBLIC_KEY"
<img width="470" alt="react-example b7e7b2dd" src="https://user-images.githubusercontent.com/13381905/168106112-2dcac89d-6a17-4961-8aa8-6dc028240b9d.png">

**Comment by fsher** [comment]
@kirksgithub hey there!

1. If I understood the question correctly, you mean the endpoint for the RPC pool? If yes, there is a `rpcUrl` prop for NotificationsButton component to override it the default
2. This public key is the `monitoring-service` public key. In order to receive web3 notifications we create a thread between the monitoring service that sends out these notifications. Hope this makes sense.

**Comment by kirksgithub** [comment]
@fsher thank you so much, integration going to be quite smooth sailing, both questions answered and resolved, I have a few more minor questions before we finalize and make an announcement - which are related to styling, here is a quick first screenshot <img width="650" alt="Screen Shot 2022-05-12 at 9 15 26 PM" src="https://user-images.githubusercontent.com/13381905/168141785-ea7be383-6769-4bc7-b56a-fde67d91a85b.png">

**Comment by fsher** [comment]
@kirksgithub that's awesome! Feel free to style the chat through `variables` prop. Provide specific overrides - colors, spacings, sizes. We've tried to make the theme intuitive, but still in progress! Please let us know if you face some problems or find any issues along the way. Thanks in advance! We are really excited to see projects like yours integrating Dialect. :)
