### ISSUE TITLE
There is no option to detect does open model or close 

### ISSUE THREAD

**Issue by AlekseiPetrovDev** [dialectlabs/react#117]
@Kiryous @fsher during one of integration we found out that there is no ability to detect status of our modal. Some project want o implement for example custom backdrop. 

Proposals: as easiest solution - add callback which will return actual state and will be triggered on setOpen action. 

` 
<NotificationsButton
   {...props}
   onStateChange={(isOpen) => {console.log(isOpen)}}
`

**Comment by fsher** [comment]
@AlekseiPetrovDev great point. I'm currently adding the ability to control overall opening/closing/managing dialect related windows. Should be added relatively soon.

**Comment by Akashmathwani** [comment]
Isn't it possible via checking UI state  like ui.open and get UI from

 const { ui, open, navigation } = useDialectUiId<ChatNavigationHelpers>(
    'dialect-bottom-chat'
  )
